// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.7
// source: customer/customer.proto

package customerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	CustomerType  string                 `protobuf:"bytes,7,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"` // individual, business
	CompanyName   string                 `protobuf:"bytes,8,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	TaxId         string                 `protobuf:"bytes,9,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	Address       string                 `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	Birthday      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Notes         string                 `protobuf:"bytes,12,opt,name=notes,proto3" json:"notes,omitempty"`
	Preferences   *structpb.Struct       `protobuf:"bytes,13,opt,name=preferences,proto3" json:"preferences,omitempty"`
	IsActive      bool                   `protobuf:"varint,14,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Vehicles      []*Vehicle             `protobuf:"bytes,15,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	CustomerNotes []*CustomerNote        `protobuf:"bytes,16,rep,name=customer_notes,json=customerNotes,proto3" json:"customer_notes,omitempty"`
	Stats         *CustomerStats         `protobuf:"bytes,17,opt,name=stats,proto3" json:"stats,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_customer_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Customer) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Customer) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Customer) GetCustomerType() string {
	if x != nil {
		return x.CustomerType
	}
	return ""
}

func (x *Customer) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *Customer) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *Customer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Customer) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *Customer) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Customer) GetPreferences() *structpb.Struct {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *Customer) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Customer) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *Customer) GetCustomerNotes() []*CustomerNote {
	if x != nil {
		return x.CustomerNotes
	}
	return nil
}

func (x *Customer) GetStats() *CustomerStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Customer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Customer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Make          string                 `protobuf:"bytes,3,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Vin           string                 `protobuf:"bytes,6,opt,name=vin,proto3" json:"vin,omitempty"`
	LicensePlate  string                 `protobuf:"bytes,7,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Color         string                 `protobuf:"bytes,8,opt,name=color,proto3" json:"color,omitempty"`
	Engine        string                 `protobuf:"bytes,9,opt,name=engine,proto3" json:"engine,omitempty"`
	Notes         string                 `protobuf:"bytes,10,opt,name=notes,proto3" json:"notes,omitempty"`
	IsActive      bool                   `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,12,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_customer_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{1}
}

func (x *Vehicle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vehicle) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Vehicle) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *Vehicle) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Vehicle) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Vehicle) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *Vehicle) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *Vehicle) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Vehicle) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *Vehicle) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Vehicle) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Vehicle) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Vehicle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Vehicle) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CustomerNote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	StaffId       string                 `protobuf:"bytes,3,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	StaffName     string                 `protobuf:"bytes,4,opt,name=staff_name,json=staffName,proto3" json:"staff_name,omitempty"`
	Note          string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"` // general, service, complaint, compliment
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerNote) Reset() {
	*x = CustomerNote{}
	mi := &file_customer_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerNote) ProtoMessage() {}

func (x *CustomerNote) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerNote.ProtoReflect.Descriptor instead.
func (*CustomerNote) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerNote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomerNote) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CustomerNote) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *CustomerNote) GetStaffName() string {
	if x != nil {
		return x.StaffName
	}
	return ""
}

func (x *CustomerNote) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CustomerNote) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CustomerNote) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CustomerStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalOrders       int32                  `protobuf:"varint,1,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	TotalSpent        float64                `protobuf:"fixed64,2,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
	AverageOrderValue float64                `protobuf:"fixed64,3,opt,name=average_order_value,json=averageOrderValue,proto3" json:"average_order_value,omitempty"`
	LastVisit         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_visit,json=lastVisit,proto3" json:"last_visit,omitempty"`
	VisitsCount       int32                  `protobuf:"varint,5,opt,name=visits_count,json=visitsCount,proto3" json:"visits_count,omitempty"`
	FavoriteCategory  string                 `protobuf:"bytes,6,opt,name=favorite_category,json=favoriteCategory,proto3" json:"favorite_category,omitempty"`
	FavoriteProducts  []string               `protobuf:"bytes,7,rep,name=favorite_products,json=favoriteProducts,proto3" json:"favorite_products,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CustomerStats) Reset() {
	*x = CustomerStats{}
	mi := &file_customer_customer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerStats) ProtoMessage() {}

func (x *CustomerStats) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerStats.ProtoReflect.Descriptor instead.
func (*CustomerStats) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{3}
}

func (x *CustomerStats) GetTotalOrders() int32 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *CustomerStats) GetTotalSpent() float64 {
	if x != nil {
		return x.TotalSpent
	}
	return 0
}

func (x *CustomerStats) GetAverageOrderValue() float64 {
	if x != nil {
		return x.AverageOrderValue
	}
	return 0
}

func (x *CustomerStats) GetLastVisit() *timestamppb.Timestamp {
	if x != nil {
		return x.LastVisit
	}
	return nil
}

func (x *CustomerStats) GetVisitsCount() int32 {
	if x != nil {
		return x.VisitsCount
	}
	return 0
}

func (x *CustomerStats) GetFavoriteCategory() string {
	if x != nil {
		return x.FavoriteCategory
	}
	return ""
}

func (x *CustomerStats) GetFavoriteProducts() []string {
	if x != nil {
		return x.FavoriteProducts
	}
	return nil
}

// Customer Requests/Responses
type ListCustomersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	CustomerType  string                 `protobuf:"bytes,3,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,4,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,7,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`          // name, created_at, last_visit, total_spent
	SortOrder     string                 `protobuf:"bytes,8,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // asc, desc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomersRequest) Reset() {
	*x = ListCustomersRequest{}
	mi := &file_customer_customer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomersRequest) ProtoMessage() {}

func (x *ListCustomersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomersRequest.ProtoReflect.Descriptor instead.
func (*ListCustomersRequest) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{4}
}

func (x *ListCustomersRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListCustomersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListCustomersRequest) GetCustomerType() string {
	if x != nil {
		return x.CustomerType
	}
	return ""
}

func (x *ListCustomersRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *ListCustomersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCustomersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCustomersRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListCustomersRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type ListCustomersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customers     []*Customer            `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomersResponse) Reset() {
	*x = ListCustomersResponse{}
	mi := &file_customer_customer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomersResponse) ProtoMessage() {}

func (x *ListCustomersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomersResponse.ProtoReflect.Descriptor instead.
func (*ListCustomersResponse) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{5}
}

func (x *ListCustomersResponse) GetCustomers() []*Customer {
	if x != nil {
		return x.Customers
	}
	return nil
}

func (x *ListCustomersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListCustomersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCustomersResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCustomersResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetCustomerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id              string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	IncludeVehicles bool                   `protobuf:"varint,3,opt,name=include_vehicles,json=includeVehicles,proto3" json:"include_vehicles,omitempty"`
	IncludeNotes    bool                   `protobuf:"varint,4,opt,name=include_notes,json=includeNotes,proto3" json:"include_notes,omitempty"`
	IncludeStats    bool                   `protobuf:"varint,5,opt,name=include_stats,json=includeStats,proto3" json:"include_stats,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	mi := &file_customer_customer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{6}
}

func (x *GetCustomerRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetCustomerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCustomerRequest) GetIncludeVehicles() bool {
	if x != nil {
		return x.IncludeVehicles
	}
	return false
}

func (x *GetCustomerRequest) GetIncludeNotes() bool {
	if x != nil {
		return x.IncludeNotes
	}
	return false
}

func (x *GetCustomerRequest) GetIncludeStats() bool {
	if x != nil {
		return x.IncludeStats
	}
	return false
}

type GetCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerResponse) Reset() {
	*x = GetCustomerResponse{}
	mi := &file_customer_customer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerResponse) ProtoMessage() {}

func (x *GetCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{7}
}

func (x *GetCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type CreateCustomerRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TenantId      string                  `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	FirstName     string                  `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                  `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                  `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                  `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	CustomerType  string                  `protobuf:"bytes,6,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`
	CompanyName   string                  `protobuf:"bytes,7,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	TaxId         string                  `protobuf:"bytes,8,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	Address       string                  `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Birthday      *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Notes         string                  `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
	Preferences   *structpb.Struct        `protobuf:"bytes,12,opt,name=preferences,proto3" json:"preferences,omitempty"`
	Vehicles      []*CreateVehicleRequest `protobuf:"bytes,13,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_customer_customer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{8}
}

func (x *CreateCustomerRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateCustomerRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateCustomerRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateCustomerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateCustomerRequest) GetCustomerType() string {
	if x != nil {
		return x.CustomerType
	}
	return ""
}

func (x *CreateCustomerRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *CreateCustomerRequest) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *CreateCustomerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateCustomerRequest) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *CreateCustomerRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CreateCustomerRequest) GetPreferences() *structpb.Struct {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *CreateCustomerRequest) GetVehicles() []*CreateVehicleRequest {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

type CreateCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerResponse) Reset() {
	*x = CreateCustomerResponse{}
	mi := &file_customer_customer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerResponse) ProtoMessage() {}

func (x *CreateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerResponse.ProtoReflect.Descriptor instead.
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type UpdateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	CustomerType  string                 `protobuf:"bytes,7,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`
	CompanyName   string                 `protobuf:"bytes,8,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	TaxId         string                 `protobuf:"bytes,9,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	Address       string                 `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	Birthday      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Notes         string                 `protobuf:"bytes,12,opt,name=notes,proto3" json:"notes,omitempty"`
	Preferences   *structpb.Struct       `protobuf:"bytes,13,opt,name=preferences,proto3" json:"preferences,omitempty"`
	IsActive      bool                   `protobuf:"varint,14,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerRequest) Reset() {
	*x = UpdateCustomerRequest{}
	mi := &file_customer_customer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerRequest) ProtoMessage() {}

func (x *UpdateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerRequest.ProtoReflect.Descriptor instead.
func (*UpdateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCustomerRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateCustomerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCustomerRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateCustomerRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateCustomerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateCustomerRequest) GetCustomerType() string {
	if x != nil {
		return x.CustomerType
	}
	return ""
}

func (x *UpdateCustomerRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *UpdateCustomerRequest) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *UpdateCustomerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateCustomerRequest) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *UpdateCustomerRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *UpdateCustomerRequest) GetPreferences() *structpb.Struct {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *UpdateCustomerRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerResponse) Reset() {
	*x = UpdateCustomerResponse{}
	mi := &file_customer_customer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerResponse) ProtoMessage() {}

func (x *UpdateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerResponse.ProtoReflect.Descriptor instead.
func (*UpdateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type DeleteCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCustomerRequest) Reset() {
	*x = DeleteCustomerRequest{}
	mi := &file_customer_customer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerRequest) ProtoMessage() {}

func (x *DeleteCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerRequest.ProtoReflect.Descriptor instead.
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCustomerRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteCustomerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCustomerResponse) Reset() {
	*x = DeleteCustomerResponse{}
	mi := &file_customer_customer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerResponse) ProtoMessage() {}

func (x *DeleteCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerResponse.ProtoReflect.Descriptor instead.
func (*DeleteCustomerResponse) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCustomerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Vehicle Requests/Responses
type ListVehiclesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Search        string                 `protobuf:"bytes,2,opt,name=search,proto3" json:"search,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,3,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesRequest) Reset() {
	*x = ListVehiclesRequest{}
	mi := &file_customer_customer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesRequest) ProtoMessage() {}

func (x *ListVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesRequest.ProtoReflect.Descriptor instead.
func (*ListVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{14}
}

func (x *ListVehiclesRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListVehiclesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListVehiclesRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

func (x *ListVehiclesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListVehiclesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicles      []*Vehicle             `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesResponse) Reset() {
	*x = ListVehiclesResponse{}
	mi := &file_customer_customer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesResponse) ProtoMessage() {}

func (x *ListVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesResponse.ProtoReflect.Descriptor instead.
func (*ListVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{15}
}

func (x *ListVehiclesResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

func (x *ListVehiclesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleRequest) Reset() {
	*x = GetVehicleRequest{}
	mi := &file_customer_customer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleRequest) ProtoMessage() {}

func (x *GetVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleRequest) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{16}
}

func (x *GetVehicleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleResponse) Reset() {
	*x = GetVehicleResponse{}
	mi := &file_customer_customer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleResponse) ProtoMessage() {}

func (x *GetVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleResponse.ProtoReflect.Descriptor instead.
func (*GetVehicleResponse) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{17}
}

func (x *GetVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type CreateVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Vin           string                 `protobuf:"bytes,5,opt,name=vin,proto3" json:"vin,omitempty"`
	LicensePlate  string                 `protobuf:"bytes,6,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Color         string                 `protobuf:"bytes,7,opt,name=color,proto3" json:"color,omitempty"`
	Engine        string                 `protobuf:"bytes,8,opt,name=engine,proto3" json:"engine,omitempty"`
	Notes         string                 `protobuf:"bytes,9,opt,name=notes,proto3" json:"notes,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVehicleRequest) Reset() {
	*x = CreateVehicleRequest{}
	mi := &file_customer_customer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleRequest) ProtoMessage() {}

func (x *CreateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleRequest.ProtoReflect.Descriptor instead.
func (*CreateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{18}
}

func (x *CreateVehicleRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateVehicleRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *CreateVehicleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateVehicleRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateVehicleRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *CreateVehicleRequest) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *CreateVehicleRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateVehicleRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *CreateVehicleRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *CreateVehicleRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVehicleResponse) Reset() {
	*x = CreateVehicleResponse{}
	mi := &file_customer_customer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleResponse) ProtoMessage() {}

func (x *CreateVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleResponse.ProtoReflect.Descriptor instead.
func (*CreateVehicleResponse) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{19}
}

func (x *CreateVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type UpdateVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Make          string                 `protobuf:"bytes,2,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Vin           string                 `protobuf:"bytes,5,opt,name=vin,proto3" json:"vin,omitempty"`
	LicensePlate  string                 `protobuf:"bytes,6,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	Color         string                 `protobuf:"bytes,7,opt,name=color,proto3" json:"color,omitempty"`
	Engine        string                 `protobuf:"bytes,8,opt,name=engine,proto3" json:"engine,omitempty"`
	Notes         string                 `protobuf:"bytes,9,opt,name=notes,proto3" json:"notes,omitempty"`
	IsActive      bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleRequest) Reset() {
	*x = UpdateVehicleRequest{}
	mi := &file_customer_customer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleRequest) ProtoMessage() {}

func (x *UpdateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleRequest.ProtoReflect.Descriptor instead.
func (*UpdateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateVehicleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateVehicleRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *UpdateVehicleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateVehicleRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UpdateVehicleRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *UpdateVehicleRequest) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *UpdateVehicleRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *UpdateVehicleRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *UpdateVehicleRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *UpdateVehicleRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpdateVehicleRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleResponse) Reset() {
	*x = UpdateVehicleResponse{}
	mi := &file_customer_customer_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleResponse) ProtoMessage() {}

func (x *UpdateVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleResponse.ProtoReflect.Descriptor instead.
func (*UpdateVehicleResponse) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type DeleteVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleRequest) Reset() {
	*x = DeleteVehicleRequest{}
	mi := &file_customer_customer_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleRequest) ProtoMessage() {}

func (x *DeleteVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleRequest.ProtoReflect.Descriptor instead.
func (*DeleteVehicleRequest) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteVehicleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVehicleResponse) Reset() {
	*x = DeleteVehicleResponse{}
	mi := &file_customer_customer_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVehicleResponse) ProtoMessage() {}

func (x *DeleteVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVehicleResponse.ProtoReflect.Descriptor instead.
func (*DeleteVehicleResponse) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteVehicleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Search Requests/Responses
type SearchCustomersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	SearchFields  string                 `protobuf:"bytes,3,opt,name=search_fields,json=searchFields,proto3" json:"search_fields,omitempty"` // name, email, phone, tax_id
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCustomersRequest) Reset() {
	*x = SearchCustomersRequest{}
	mi := &file_customer_customer_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCustomersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCustomersRequest) ProtoMessage() {}

func (x *SearchCustomersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCustomersRequest.ProtoReflect.Descriptor instead.
func (*SearchCustomersRequest) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{24}
}

func (x *SearchCustomersRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SearchCustomersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchCustomersRequest) GetSearchFields() string {
	if x != nil {
		return x.SearchFields
	}
	return ""
}

func (x *SearchCustomersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchCustomersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customers     []*Customer            `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCustomersResponse) Reset() {
	*x = SearchCustomersResponse{}
	mi := &file_customer_customer_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCustomersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCustomersResponse) ProtoMessage() {}

func (x *SearchCustomersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCustomersResponse.ProtoReflect.Descriptor instead.
func (*SearchCustomersResponse) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{25}
}

func (x *SearchCustomersResponse) GetCustomers() []*Customer {
	if x != nil {
		return x.Customers
	}
	return nil
}

func (x *SearchCustomersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Customer History Requests/Responses
type GetCustomerHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // orders, appointments, notes
	DateFrom      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerHistoryRequest) Reset() {
	*x = GetCustomerHistoryRequest{}
	mi := &file_customer_customer_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerHistoryRequest) ProtoMessage() {}

func (x *GetCustomerHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerHistoryRequest) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{26}
}

func (x *GetCustomerHistoryRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetCustomerHistoryRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetCustomerHistoryRequest) GetDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *GetCustomerHistoryRequest) GetDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTo
	}
	return nil
}

func (x *GetCustomerHistoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCustomerHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CustomerHistoryItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // order, appointment, note, payment
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerHistoryItem) Reset() {
	*x = CustomerHistoryItem{}
	mi := &file_customer_customer_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerHistoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerHistoryItem) ProtoMessage() {}

func (x *CustomerHistoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerHistoryItem.ProtoReflect.Descriptor instead.
func (*CustomerHistoryItem) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{27}
}

func (x *CustomerHistoryItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CustomerHistoryItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CustomerHistoryItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CustomerHistoryItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CustomerHistoryItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CustomerHistoryItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CustomerHistoryItem) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CustomerHistoryItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetCustomerHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CustomerHistoryItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerHistoryResponse) Reset() {
	*x = GetCustomerHistoryResponse{}
	mi := &file_customer_customer_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerHistoryResponse) ProtoMessage() {}

func (x *GetCustomerHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerHistoryResponse) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{28}
}

func (x *GetCustomerHistoryResponse) GetItems() []*CustomerHistoryItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetCustomerHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AddCustomerNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCustomerNoteRequest) Reset() {
	*x = AddCustomerNoteRequest{}
	mi := &file_customer_customer_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCustomerNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCustomerNoteRequest) ProtoMessage() {}

func (x *AddCustomerNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCustomerNoteRequest.ProtoReflect.Descriptor instead.
func (*AddCustomerNoteRequest) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{29}
}

func (x *AddCustomerNoteRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AddCustomerNoteRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *AddCustomerNoteRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type AddCustomerNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          *CustomerNote          `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCustomerNoteResponse) Reset() {
	*x = AddCustomerNoteResponse{}
	mi := &file_customer_customer_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCustomerNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCustomerNoteResponse) ProtoMessage() {}

func (x *AddCustomerNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_customer_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCustomerNoteResponse.ProtoReflect.Descriptor instead.
func (*AddCustomerNoteResponse) Descriptor() ([]byte, []int) {
	return file_customer_customer_proto_rawDescGZIP(), []int{30}
}

func (x *AddCustomerNoteResponse) GetNote() *CustomerNote {
	if x != nil {
		return x.Note
	}
	return nil
}

var File_customer_customer_proto protoreflect.FileDescriptor

const file_customer_customer_proto_rawDesc = "" +
	"\n" +
	"\x17customer/customer.proto\x12\vcustomer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xda\x05\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12#\n" +
	"\rcustomer_type\x18\a \x01(\tR\fcustomerType\x12!\n" +
	"\fcompany_name\x18\b \x01(\tR\vcompanyName\x12\x15\n" +
	"\x06tax_id\x18\t \x01(\tR\x05taxId\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x126\n" +
	"\bbirthday\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\x12\x14\n" +
	"\x05notes\x18\f \x01(\tR\x05notes\x129\n" +
	"\vpreferences\x18\r \x01(\v2\x17.google.protobuf.StructR\vpreferences\x12\x1b\n" +
	"\tis_active\x18\x0e \x01(\bR\bisActive\x120\n" +
	"\bvehicles\x18\x0f \x03(\v2\x14.customer.v1.VehicleR\bvehicles\x12@\n" +
	"\x0ecustomer_notes\x18\x10 \x03(\v2\x19.customer.v1.CustomerNoteR\rcustomerNotes\x120\n" +
	"\x05stats\x18\x11 \x01(\v2\x1a.customer.v1.CustomerStatsR\x05stats\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbb\x03\n" +
	"\aVehicle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x12\n" +
	"\x04make\x18\x03 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x10\n" +
	"\x03vin\x18\x06 \x01(\tR\x03vin\x12#\n" +
	"\rlicense_plate\x18\a \x01(\tR\flicensePlate\x12\x14\n" +
	"\x05color\x18\b \x01(\tR\x05color\x12\x16\n" +
	"\x06engine\x18\t \x01(\tR\x06engine\x12\x14\n" +
	"\x05notes\x18\n" +
	" \x01(\tR\x05notes\x12\x1b\n" +
	"\tis_active\x18\v \x01(\bR\bisActive\x123\n" +
	"\bmetadata\x18\f \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdc\x01\n" +
	"\fCustomerNote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x19\n" +
	"\bstaff_id\x18\x03 \x01(\tR\astaffId\x12\x1d\n" +
	"\n" +
	"staff_name\x18\x04 \x01(\tR\tstaffName\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xbb\x02\n" +
	"\rCustomerStats\x12!\n" +
	"\ftotal_orders\x18\x01 \x01(\x05R\vtotalOrders\x12\x1f\n" +
	"\vtotal_spent\x18\x02 \x01(\x01R\n" +
	"totalSpent\x12.\n" +
	"\x13average_order_value\x18\x03 \x01(\x01R\x11averageOrderValue\x129\n" +
	"\n" +
	"last_visit\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tlastVisit\x12!\n" +
	"\fvisits_count\x18\x05 \x01(\x05R\vvisitsCount\x12+\n" +
	"\x11favorite_category\x18\x06 \x01(\tR\x10favoriteCategory\x12+\n" +
	"\x11favorite_products\x18\a \x03(\tR\x10favoriteProducts\"\xf3\x01\n" +
	"\x14ListCustomersRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12#\n" +
	"\rcustomer_type\x18\x03 \x01(\tR\fcustomerType\x12\x1f\n" +
	"\vactive_only\x18\x04 \x01(\bR\n" +
	"activeOnly\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\a \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\b \x01(\tR\tsortOrder\"\xad\x01\n" +
	"\x15ListCustomersResponse\x123\n" +
	"\tcustomers\x18\x01 \x03(\v2\x15.customer.v1.CustomerR\tcustomers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\xb6\x01\n" +
	"\x12GetCustomerRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12)\n" +
	"\x10include_vehicles\x18\x03 \x01(\bR\x0fincludeVehicles\x12#\n" +
	"\rinclude_notes\x18\x04 \x01(\bR\fincludeNotes\x12#\n" +
	"\rinclude_stats\x18\x05 \x01(\bR\fincludeStats\"H\n" +
	"\x13GetCustomerResponse\x121\n" +
	"\bcustomer\x18\x01 \x01(\v2\x15.customer.v1.CustomerR\bcustomer\"\xdd\x03\n" +
	"\x15CreateCustomerRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12#\n" +
	"\rcustomer_type\x18\x06 \x01(\tR\fcustomerType\x12!\n" +
	"\fcompany_name\x18\a \x01(\tR\vcompanyName\x12\x15\n" +
	"\x06tax_id\x18\b \x01(\tR\x05taxId\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x126\n" +
	"\bbirthday\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\x12\x14\n" +
	"\x05notes\x18\v \x01(\tR\x05notes\x129\n" +
	"\vpreferences\x18\f \x01(\v2\x17.google.protobuf.StructR\vpreferences\x12=\n" +
	"\bvehicles\x18\r \x03(\v2!.customer.v1.CreateVehicleRequestR\bvehicles\"K\n" +
	"\x16CreateCustomerResponse\x121\n" +
	"\bcustomer\x18\x01 \x01(\v2\x15.customer.v1.CustomerR\bcustomer\"\xcb\x03\n" +
	"\x15UpdateCustomerRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12#\n" +
	"\rcustomer_type\x18\a \x01(\tR\fcustomerType\x12!\n" +
	"\fcompany_name\x18\b \x01(\tR\vcompanyName\x12\x15\n" +
	"\x06tax_id\x18\t \x01(\tR\x05taxId\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x126\n" +
	"\bbirthday\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bbirthday\x12\x14\n" +
	"\x05notes\x18\f \x01(\tR\x05notes\x129\n" +
	"\vpreferences\x18\r \x01(\v2\x17.google.protobuf.StructR\vpreferences\x12\x1b\n" +
	"\tis_active\x18\x0e \x01(\bR\bisActive\"K\n" +
	"\x16UpdateCustomerResponse\x121\n" +
	"\bcustomer\x18\x01 \x01(\v2\x15.customer.v1.CustomerR\bcustomer\"D\n" +
	"\x15DeleteCustomerRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"2\n" +
	"\x16DeleteCustomerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x99\x01\n" +
	"\x13ListVehiclesRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x16\n" +
	"\x06search\x18\x02 \x01(\tR\x06search\x12\x1f\n" +
	"\vactive_only\x18\x03 \x01(\bR\n" +
	"activeOnly\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"^\n" +
	"\x14ListVehiclesResponse\x120\n" +
	"\bvehicles\x18\x01 \x03(\v2\x14.customer.v1.VehicleR\bvehicles\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"#\n" +
	"\x11GetVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x12GetVehicleResponse\x12.\n" +
	"\avehicle\x18\x01 \x01(\v2\x14.customer.v1.VehicleR\avehicle\"\xa5\x02\n" +
	"\x14CreateVehicleRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x10\n" +
	"\x03vin\x18\x05 \x01(\tR\x03vin\x12#\n" +
	"\rlicense_plate\x18\x06 \x01(\tR\flicensePlate\x12\x14\n" +
	"\x05color\x18\a \x01(\tR\x05color\x12\x16\n" +
	"\x06engine\x18\b \x01(\tR\x06engine\x12\x14\n" +
	"\x05notes\x18\t \x01(\tR\x05notes\x123\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\bmetadata\"G\n" +
	"\x15CreateVehicleResponse\x12.\n" +
	"\avehicle\x18\x01 \x01(\v2\x14.customer.v1.VehicleR\avehicle\"\xb1\x02\n" +
	"\x14UpdateVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04make\x18\x02 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x10\n" +
	"\x03vin\x18\x05 \x01(\tR\x03vin\x12#\n" +
	"\rlicense_plate\x18\x06 \x01(\tR\flicensePlate\x12\x14\n" +
	"\x05color\x18\a \x01(\tR\x05color\x12\x16\n" +
	"\x06engine\x18\b \x01(\tR\x06engine\x12\x14\n" +
	"\x05notes\x18\t \x01(\tR\x05notes\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x123\n" +
	"\bmetadata\x18\v \x01(\v2\x17.google.protobuf.StructR\bmetadata\"G\n" +
	"\x15UpdateVehicleResponse\x12.\n" +
	"\avehicle\x18\x01 \x01(\v2\x14.customer.v1.VehicleR\avehicle\"&\n" +
	"\x14DeleteVehicleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteVehicleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x86\x01\n" +
	"\x16SearchCustomersRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12#\n" +
	"\rsearch_fields\x18\x03 \x01(\tR\fsearchFields\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"d\n" +
	"\x17SearchCustomersResponse\x123\n" +
	"\tcustomers\x18\x01 \x03(\v2\x15.customer.v1.CustomerR\tcustomers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xe8\x01\n" +
	"\x19GetCustomerHistoryRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x127\n" +
	"\tdate_from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bdateFrom\x123\n" +
	"\adate_to\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06dateTo\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"\x89\x02\n" +
	"\x13CustomerHistoryItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12+\n" +
	"\x04data\x18\a \x01(\v2\x17.google.protobuf.StructR\x04data\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"j\n" +
	"\x1aGetCustomerHistoryResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .customer.v1.CustomerHistoryItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"a\n" +
	"\x16AddCustomerNoteRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"H\n" +
	"\x17AddCustomerNoteResponse\x12-\n" +
	"\x04note\x18\x01 \x01(\v2\x19.customer.v1.CustomerNoteR\x04note2\x9b\t\n" +
	"\x0fCustomerService\x12V\n" +
	"\rListCustomers\x12!.customer.v1.ListCustomersRequest\x1a\".customer.v1.ListCustomersResponse\x12P\n" +
	"\vGetCustomer\x12\x1f.customer.v1.GetCustomerRequest\x1a .customer.v1.GetCustomerResponse\x12Y\n" +
	"\x0eCreateCustomer\x12\".customer.v1.CreateCustomerRequest\x1a#.customer.v1.CreateCustomerResponse\x12Y\n" +
	"\x0eUpdateCustomer\x12\".customer.v1.UpdateCustomerRequest\x1a#.customer.v1.UpdateCustomerResponse\x12Y\n" +
	"\x0eDeleteCustomer\x12\".customer.v1.DeleteCustomerRequest\x1a#.customer.v1.DeleteCustomerResponse\x12S\n" +
	"\fListVehicles\x12 .customer.v1.ListVehiclesRequest\x1a!.customer.v1.ListVehiclesResponse\x12M\n" +
	"\n" +
	"GetVehicle\x12\x1e.customer.v1.GetVehicleRequest\x1a\x1f.customer.v1.GetVehicleResponse\x12V\n" +
	"\rCreateVehicle\x12!.customer.v1.CreateVehicleRequest\x1a\".customer.v1.CreateVehicleResponse\x12V\n" +
	"\rUpdateVehicle\x12!.customer.v1.UpdateVehicleRequest\x1a\".customer.v1.UpdateVehicleResponse\x12V\n" +
	"\rDeleteVehicle\x12!.customer.v1.DeleteVehicleRequest\x1a\".customer.v1.DeleteVehicleResponse\x12\\\n" +
	"\x0fSearchCustomers\x12#.customer.v1.SearchCustomersRequest\x1a$.customer.v1.SearchCustomersResponse\x12e\n" +
	"\x12GetCustomerHistory\x12&.customer.v1.GetCustomerHistoryRequest\x1a'.customer.v1.GetCustomerHistoryResponse\x12\\\n" +
	"\x0fAddCustomerNote\x12#.customer.v1.AddCustomerNoteRequest\x1a$.customer.v1.AddCustomerNoteResponseBKZIgithub.com/encomos/api-encomos/customer-service/proto/customer;customerpbb\x06proto3"

var (
	file_customer_customer_proto_rawDescOnce sync.Once
	file_customer_customer_proto_rawDescData []byte
)

func file_customer_customer_proto_rawDescGZIP() []byte {
	file_customer_customer_proto_rawDescOnce.Do(func() {
		file_customer_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customer_customer_proto_rawDesc), len(file_customer_customer_proto_rawDesc)))
	})
	return file_customer_customer_proto_rawDescData
}

var file_customer_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_customer_customer_proto_goTypes = []any{
	(*Customer)(nil),                   // 0: customer.v1.Customer
	(*Vehicle)(nil),                    // 1: customer.v1.Vehicle
	(*CustomerNote)(nil),               // 2: customer.v1.CustomerNote
	(*CustomerStats)(nil),              // 3: customer.v1.CustomerStats
	(*ListCustomersRequest)(nil),       // 4: customer.v1.ListCustomersRequest
	(*ListCustomersResponse)(nil),      // 5: customer.v1.ListCustomersResponse
	(*GetCustomerRequest)(nil),         // 6: customer.v1.GetCustomerRequest
	(*GetCustomerResponse)(nil),        // 7: customer.v1.GetCustomerResponse
	(*CreateCustomerRequest)(nil),      // 8: customer.v1.CreateCustomerRequest
	(*CreateCustomerResponse)(nil),     // 9: customer.v1.CreateCustomerResponse
	(*UpdateCustomerRequest)(nil),      // 10: customer.v1.UpdateCustomerRequest
	(*UpdateCustomerResponse)(nil),     // 11: customer.v1.UpdateCustomerResponse
	(*DeleteCustomerRequest)(nil),      // 12: customer.v1.DeleteCustomerRequest
	(*DeleteCustomerResponse)(nil),     // 13: customer.v1.DeleteCustomerResponse
	(*ListVehiclesRequest)(nil),        // 14: customer.v1.ListVehiclesRequest
	(*ListVehiclesResponse)(nil),       // 15: customer.v1.ListVehiclesResponse
	(*GetVehicleRequest)(nil),          // 16: customer.v1.GetVehicleRequest
	(*GetVehicleResponse)(nil),         // 17: customer.v1.GetVehicleResponse
	(*CreateVehicleRequest)(nil),       // 18: customer.v1.CreateVehicleRequest
	(*CreateVehicleResponse)(nil),      // 19: customer.v1.CreateVehicleResponse
	(*UpdateVehicleRequest)(nil),       // 20: customer.v1.UpdateVehicleRequest
	(*UpdateVehicleResponse)(nil),      // 21: customer.v1.UpdateVehicleResponse
	(*DeleteVehicleRequest)(nil),       // 22: customer.v1.DeleteVehicleRequest
	(*DeleteVehicleResponse)(nil),      // 23: customer.v1.DeleteVehicleResponse
	(*SearchCustomersRequest)(nil),     // 24: customer.v1.SearchCustomersRequest
	(*SearchCustomersResponse)(nil),    // 25: customer.v1.SearchCustomersResponse
	(*GetCustomerHistoryRequest)(nil),  // 26: customer.v1.GetCustomerHistoryRequest
	(*CustomerHistoryItem)(nil),        // 27: customer.v1.CustomerHistoryItem
	(*GetCustomerHistoryResponse)(nil), // 28: customer.v1.GetCustomerHistoryResponse
	(*AddCustomerNoteRequest)(nil),     // 29: customer.v1.AddCustomerNoteRequest
	(*AddCustomerNoteResponse)(nil),    // 30: customer.v1.AddCustomerNoteResponse
	(*timestamppb.Timestamp)(nil),      // 31: google.protobuf.Timestamp
	(*structpb.Struct)(nil),            // 32: google.protobuf.Struct
}
var file_customer_customer_proto_depIdxs = []int32{
	31, // 0: customer.v1.Customer.birthday:type_name -> google.protobuf.Timestamp
	32, // 1: customer.v1.Customer.preferences:type_name -> google.protobuf.Struct
	1,  // 2: customer.v1.Customer.vehicles:type_name -> customer.v1.Vehicle
	2,  // 3: customer.v1.Customer.customer_notes:type_name -> customer.v1.CustomerNote
	3,  // 4: customer.v1.Customer.stats:type_name -> customer.v1.CustomerStats
	31, // 5: customer.v1.Customer.created_at:type_name -> google.protobuf.Timestamp
	31, // 6: customer.v1.Customer.updated_at:type_name -> google.protobuf.Timestamp
	32, // 7: customer.v1.Vehicle.metadata:type_name -> google.protobuf.Struct
	31, // 8: customer.v1.Vehicle.created_at:type_name -> google.protobuf.Timestamp
	31, // 9: customer.v1.Vehicle.updated_at:type_name -> google.protobuf.Timestamp
	31, // 10: customer.v1.CustomerNote.created_at:type_name -> google.protobuf.Timestamp
	31, // 11: customer.v1.CustomerStats.last_visit:type_name -> google.protobuf.Timestamp
	0,  // 12: customer.v1.ListCustomersResponse.customers:type_name -> customer.v1.Customer
	0,  // 13: customer.v1.GetCustomerResponse.customer:type_name -> customer.v1.Customer
	31, // 14: customer.v1.CreateCustomerRequest.birthday:type_name -> google.protobuf.Timestamp
	32, // 15: customer.v1.CreateCustomerRequest.preferences:type_name -> google.protobuf.Struct
	18, // 16: customer.v1.CreateCustomerRequest.vehicles:type_name -> customer.v1.CreateVehicleRequest
	0,  // 17: customer.v1.CreateCustomerResponse.customer:type_name -> customer.v1.Customer
	31, // 18: customer.v1.UpdateCustomerRequest.birthday:type_name -> google.protobuf.Timestamp
	32, // 19: customer.v1.UpdateCustomerRequest.preferences:type_name -> google.protobuf.Struct
	0,  // 20: customer.v1.UpdateCustomerResponse.customer:type_name -> customer.v1.Customer
	1,  // 21: customer.v1.ListVehiclesResponse.vehicles:type_name -> customer.v1.Vehicle
	1,  // 22: customer.v1.GetVehicleResponse.vehicle:type_name -> customer.v1.Vehicle
	32, // 23: customer.v1.CreateVehicleRequest.metadata:type_name -> google.protobuf.Struct
	1,  // 24: customer.v1.CreateVehicleResponse.vehicle:type_name -> customer.v1.Vehicle
	32, // 25: customer.v1.UpdateVehicleRequest.metadata:type_name -> google.protobuf.Struct
	1,  // 26: customer.v1.UpdateVehicleResponse.vehicle:type_name -> customer.v1.Vehicle
	0,  // 27: customer.v1.SearchCustomersResponse.customers:type_name -> customer.v1.Customer
	31, // 28: customer.v1.GetCustomerHistoryRequest.date_from:type_name -> google.protobuf.Timestamp
	31, // 29: customer.v1.GetCustomerHistoryRequest.date_to:type_name -> google.protobuf.Timestamp
	32, // 30: customer.v1.CustomerHistoryItem.data:type_name -> google.protobuf.Struct
	31, // 31: customer.v1.CustomerHistoryItem.created_at:type_name -> google.protobuf.Timestamp
	27, // 32: customer.v1.GetCustomerHistoryResponse.items:type_name -> customer.v1.CustomerHistoryItem
	2,  // 33: customer.v1.AddCustomerNoteResponse.note:type_name -> customer.v1.CustomerNote
	4,  // 34: customer.v1.CustomerService.ListCustomers:input_type -> customer.v1.ListCustomersRequest
	6,  // 35: customer.v1.CustomerService.GetCustomer:input_type -> customer.v1.GetCustomerRequest
	8,  // 36: customer.v1.CustomerService.CreateCustomer:input_type -> customer.v1.CreateCustomerRequest
	10, // 37: customer.v1.CustomerService.UpdateCustomer:input_type -> customer.v1.UpdateCustomerRequest
	12, // 38: customer.v1.CustomerService.DeleteCustomer:input_type -> customer.v1.DeleteCustomerRequest
	14, // 39: customer.v1.CustomerService.ListVehicles:input_type -> customer.v1.ListVehiclesRequest
	16, // 40: customer.v1.CustomerService.GetVehicle:input_type -> customer.v1.GetVehicleRequest
	18, // 41: customer.v1.CustomerService.CreateVehicle:input_type -> customer.v1.CreateVehicleRequest
	20, // 42: customer.v1.CustomerService.UpdateVehicle:input_type -> customer.v1.UpdateVehicleRequest
	22, // 43: customer.v1.CustomerService.DeleteVehicle:input_type -> customer.v1.DeleteVehicleRequest
	24, // 44: customer.v1.CustomerService.SearchCustomers:input_type -> customer.v1.SearchCustomersRequest
	26, // 45: customer.v1.CustomerService.GetCustomerHistory:input_type -> customer.v1.GetCustomerHistoryRequest
	29, // 46: customer.v1.CustomerService.AddCustomerNote:input_type -> customer.v1.AddCustomerNoteRequest
	5,  // 47: customer.v1.CustomerService.ListCustomers:output_type -> customer.v1.ListCustomersResponse
	7,  // 48: customer.v1.CustomerService.GetCustomer:output_type -> customer.v1.GetCustomerResponse
	9,  // 49: customer.v1.CustomerService.CreateCustomer:output_type -> customer.v1.CreateCustomerResponse
	11, // 50: customer.v1.CustomerService.UpdateCustomer:output_type -> customer.v1.UpdateCustomerResponse
	13, // 51: customer.v1.CustomerService.DeleteCustomer:output_type -> customer.v1.DeleteCustomerResponse
	15, // 52: customer.v1.CustomerService.ListVehicles:output_type -> customer.v1.ListVehiclesResponse
	17, // 53: customer.v1.CustomerService.GetVehicle:output_type -> customer.v1.GetVehicleResponse
	19, // 54: customer.v1.CustomerService.CreateVehicle:output_type -> customer.v1.CreateVehicleResponse
	21, // 55: customer.v1.CustomerService.UpdateVehicle:output_type -> customer.v1.UpdateVehicleResponse
	23, // 56: customer.v1.CustomerService.DeleteVehicle:output_type -> customer.v1.DeleteVehicleResponse
	25, // 57: customer.v1.CustomerService.SearchCustomers:output_type -> customer.v1.SearchCustomersResponse
	28, // 58: customer.v1.CustomerService.GetCustomerHistory:output_type -> customer.v1.GetCustomerHistoryResponse
	30, // 59: customer.v1.CustomerService.AddCustomerNote:output_type -> customer.v1.AddCustomerNoteResponse
	47, // [47:60] is the sub-list for method output_type
	34, // [34:47] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_customer_customer_proto_init() }
func file_customer_customer_proto_init() {
	if File_customer_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customer_customer_proto_rawDesc), len(file_customer_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_customer_customer_proto_goTypes,
		DependencyIndexes: file_customer_customer_proto_depIdxs,
		MessageInfos:      file_customer_customer_proto_msgTypes,
	}.Build()
	File_customer_customer_proto = out.File
	file_customer_customer_proto_goTypes = nil
	file_customer_customer_proto_depIdxs = nil
}
